gitlabpostgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=123456
    - DB_NAME=gitlabhq_production
  volumes:
    - /var/data/gitlab/postgresql:/var/lib/postgresql
gitlabredis:
  image: sameersbn/redis:latest
  volumes:
    - /var/data/gitlab/redis:/var/lib/redis
gitlab:
  image: sameersbn/gitlab:7.11.4
  links:
    - gitlabredis:redisio
    - gitlabpostgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Asia/Kolkata
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=www.163.com
    - SMTP_HOST=smtp.163.com
    - SMTP_PORT=25
    - SMTP_USER=liuhong1.happy@163.com
    - SMTP_PASS=969713145230
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=liuhong1.happy@163.com
    - GITLAB_EMAIL_REPLY_TO=liuhong1.happy@163.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /var/data/gitlab/gitlab:/home/git/data
